version: '3.9'

services:
  backend:
    build:
      context: back-end
      dockerfile: Dockerfile
    container_name: dividend-tool-back-end
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dividend_tool
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: front-end
    container_name: dividend-tool-front-end
    ports:
      - '3000:80'
    depends_on:
      - backend

  db:
    image: 'postgres:13'
    container_name: dividend-tool-postgres
    environment:
      - POSTGRES_DB=dividend_tool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data:
